sudo: false
git:
  depth: 1
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.5
  - php: 5.6
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.6
    env: PHPUNIT_COVERAGE="--coverage-clover=coverage.xml"
  - php: 7.0
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 7.0
  - php: 7.1
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 7.1
  - php: nightly
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: nightly
  allow_failures:
  - php: nightly
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: nightly
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- stty cols 120
- |
  if [ -z "$PHPUNIT_COVERAGE" ]; then
      phpenv config-rm xdebug.ini || echo "xdebug not available"
  fi
install:
- composer self-update
- composer config -g repositories.asset-packagist composer https://asset-packagist.org
- travis_retry composer update --no-interaction --prefer-stable --prefer-dist $COMPOSER_LOWEST
- composer show
script:
- vendor/bin/phpunit $PHPUNIT_COVERAGE
after_success:
- |
  if [ -n "$PHPUNIT_COVERAGE" ]; then
      travis_retry wget https://codecov.io/bash
      bash ./bash
  fi
after_script:
- |
  if [ -n "$PHPUNIT_COVERAGE" ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  fi
notifications:
  slack:
    on_pull_requests: false
    rooms:
      secure: agDMduMbSn+eOnO8daglmCP0nmdrILOj9lGMw9Bb6zK/ou1ZJTU/HEJ+kXaKC+XWeCe8Z265Izzl4SjOCVjw5aGzrlbpF8LeNIltdjzYrKr3/GInUEe3uWj8rAiK+MeFDpUY3t/R/oVk4kjU0cvigT4/LWhQD3HqlTR9h3Tox+uNxnQ0gSPs0zlZ3d2xTTSvvtP1dU8D0JVC3jvXUuhoEhjDdqeEPTiKuO49t7lMPamd/sfMnKkT8f9fBu6t7zuhaUAKdRpFLmVo1Yi3X3l7yktl4VTYFfo5CT5IFtCK9Jc8vMgL3y7hqT73UoiyOa9kZgXxZnUNZ9BQh4+2TlRYfjeCm192N6TlxiX+MG3hgJQlvP0sSP9urVt2KlLa0r1quZfV3mp6OrmzVE4oYgzzcqPYs5rJUV/yzAmIuQazfAk9jM0VZviLkORBNcIL/0/FkGELV5jIw795Tj5yJoY/Bin8tt607EqFeOjmOSqIG5tgGuHYR2gPO/pZId2yLiiALoKaVgsINXVvxDyPg8KfjoWcnh2qv0H3R30J+uMt7nWmUsiB9b3qN/hqm83+vvCg11eteWwkeZplLbGimeBYyf5V04hqkyc33Fjworh5NeUVrt7uINRz9weAU7oWedE6veAdveGfIHs0pESyWXQ/YCuVxJ8LggbDuA4EMDKM6uw=
